name: Build and Test Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0.42-debian
        env:
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_DATABASE: school_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Add execute permission to mvnw
      run: |
        cd Project
        chmod +x student-service/mvnw
        chmod +x teacher-service/mvnw
        chmod +x user-service/mvnw
    
    - name: Build Backend Services
      run: |
        cd Project/student-service && ./mvnw clean package -DskipTests
        cd ../teacher-service && ./mvnw clean package -DskipTests
        cd ../user-service && ./mvnw clean package -DskipTests
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'Project/frontend/package-lock.json'
    
    - name: Install Frontend Dependencies
      working-directory: Project/frontend
      run: npm install
    
    - name: Build Frontend
      working-directory: Project/frontend
      run: CI=false npm run build
    
    - name: Run Tests
      run: |
        cd Project/student-service && ./mvnw test
        cd ../teacher-service && ./mvnw test
        cd ../user-service && ./mvnw test

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test # This job depends on the build-and-test job
    
    steps:
    - uses: actions/checkout@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image for user-service
      uses: docker/build-push-action@v4
      with:
        context: ./Project/user-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    - name: Build and Push Docker Image for student-service
      uses: docker/build-push-action@v4
      with:
        context: ./Project/student-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/student-service:latest

    - name: Build and Push Docker Image for teacher-service
      uses: docker/build-push-action@v4
      with:
        context: ./Project/teacher-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/teacher-service:latest

    - name: Build and Push Docker Image for frontend
      uses: docker/build-push-action@v4
      with:
        context: ./Project/frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest 
